### PR TITLE
enhanced setup description and systemd unit file

### PR DESCRIPTION
**Pull request by bb-Ricardo**
Tested installations on Ubuntu and CentOS.

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
any chance to get this merged?

**Comment by sieren** [comment]
hurray for another dead repo 👎

**Comment by NerdyProjects** [comment]
Well, I guess we mostly publish the projects we use but don't actively maintain them :-) Also, we don't even use this project anymore... Would you prefer having the code unavailable?

**Comment by bb-Ricardo** [comment]
Hi, as mentioned in the other PR I would love to take over the repo.

If you don't mind you could transfer the repo: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

That would be great.

**Comment by NerdyProjects** [comment]
Sorry, I completely missed that. Unfortunately, it doesn't work:

`bb-Ricardo/fritzinfluxdb already exists and You can only transfer a repository from an organization to yourself at this time `

**Comment by NerdyProjects** [comment]
I could make you a maintainer here in the project if you like?

**Comment by bb-Ricardo** [comment]
That would be great.

**Comment by bb-Ricardo** [comment]
> I could make you a maintainer here in the project if you like?

Thank you very much

**Pull request merged**
